import type { UiLanguage } from "@/lib/i18n";

export const agentCopy = {
  ja: {
    shoppingTitle: "ショッピング判断",
    outingTitle: "おでかけ判断",
    reading: "依頼を整理しています。",
    retrievingShopping: "条件に合う商品を確認しています。",
    retrievingOuting: "場所、天気、周辺候補を確認しています。",
    needsClarification: "確認が必要です",
    unsupported: "対応範囲外",
    ready: "候補を比較できます",
    degraded: "一部の情報を確認できませんでした",
    failed: "情報を取得できませんでした",
    aborted: "実行を中止しました",
    productAction: "商品ページを開く",
    placeAction: "場所を開く",
    unknownSeller: "販売元情報なし",
    noReview: "レビュー情報なし",
    noStation: "最寄り駅情報なし",
    noAddress: "住所情報なし",
    unknownOpeningHours: "営業時間は取得元で確認してください。",
    unverifiedSize: "寸法情報が返されていないため、省スペース性は未確認です。",
    unverifiedWeather:
      "指定日時は Yahoo! JAPAN Weather の返却範囲外です。表示候補は天気による適否を確定していません。",
    heuristicIndoor: "施設カテゴリから雨天向きと推定した目安です。",
    sourceMissing: "取得元が返していない項目は不明として扱います。",
    budgetConstraint: "予算",
    reviewConstraint: "レビュー",
    compactConstraint: "省スペース",
    activityConstraint: "希望する過ごし方",
    weatherConstraint: "指定日時の天気",
    distanceFactor: "アクセス",
    queryFactor: "検索条件との一致",
    reviewFactor: "評価",
    reviewConfidenceFactor: "評価件数",
    budgetFactor: "予算適合",
    completenessFactor: "情報の充実度",
    activityFactor: "施設カテゴリ",
    weatherFactor: "雨天適合の目安",
    modelParser: "OpenAI Responses / Structured Outputs",
    ruleParser: "決定的ルール解析",
    formatter: "証拠検証済みフォーマッター"
  },
  en: {
    shoppingTitle: "Shopping decision",
    outingTitle: "Outing decision",
    reading: "Organizing your request.",
    retrievingShopping: "Checking products against your constraints.",
    retrievingOuting: "Checking the area, weather, and nearby options.",
    needsClarification: "One detail is needed",
    unsupported: "Outside the current scope",
    ready: "Options are ready to compare",
    degraded: "Some information could not be verified",
    failed: "Could not retrieve the information",
    aborted: "Run canceled",
    productAction: "Open product page",
    placeAction: "Open place",
    unknownSeller: "Seller not returned",
    noReview: "Review data not returned",
    noStation: "Nearest station not returned",
    noAddress: "Address not returned",
    unknownOpeningHours: "Check opening hours at the source before visiting.",
    unverifiedSize: "The source returned no dimensions, so compactness is unverified.",
    unverifiedWeather:
      "The requested time is outside the Yahoo! JAPAN Weather response window. Weather suitability is not confirmed.",
    heuristicIndoor: "Rain suitability is a category-level heuristic.",
    sourceMissing: "Fields not returned by the source remain unknown.",
    budgetConstraint: "Budget",
    reviewConstraint: "Reviews",
    compactConstraint: "Compactness",
    activityConstraint: "Activity preference",
    weatherConstraint: "Weather at requested time",
    distanceFactor: "Access",
    queryFactor: "Query match",
    reviewFactor: "Rating",
    reviewConfidenceFactor: "Review confidence",
    budgetFactor: "Budget fit",
    completenessFactor: "Data completeness",
    activityFactor: "Category match",
    weatherFactor: "Rain-suitability heuristic",
    modelParser: "OpenAI Responses / Structured Outputs",
    ruleParser: "Deterministic parser",
    formatter: "Evidence-validated formatter"
  },
  zh: {
    shoppingTitle: "购物判断",
    outingTitle: "外出判断",
    reading: "正在整理你的需求。",
    retrievingShopping: "正在按条件确认商品。",
    retrievingOuting: "正在确认地点、天气和附近候选。",
    needsClarification: "还需要确认一项信息",
    unsupported: "暂不支持这类请求",
    ready: "候选已可以比较",
    degraded: "部分信息无法确认",
    failed: "无法获取所需信息",
    aborted: "已停止运行",
    productAction: "打开商品页",
    placeAction: "打开地点",
    unknownSeller: "未返回卖家信息",
    noReview: "未返回评价信息",
    noStation: "未返回最近车站",
    noAddress: "未返回地址",
    unknownOpeningHours: "出发前请在来源页面确认营业时间。",
    unverifiedSize: "来源没有返回尺寸，因此无法确认是否省空间。",
    unverifiedWeather:
      "指定时间不在 Yahoo! JAPAN Weather 返回范围内，无法确认候选是否适合当时天气。",
    heuristicIndoor: "是否适合雨天仅依据设施类别进行推断。",
    sourceMissing: "来源未返回的字段会保持为未知。",
    budgetConstraint: "预算",
    reviewConstraint: "评价",
    compactConstraint: "省空间",
    activityConstraint: "活动偏好",
    weatherConstraint: "指定时间的天气",
    distanceFactor: "交通便利度",
    queryFactor: "搜索条件匹配",
    reviewFactor: "评分",
    reviewConfidenceFactor: "评价可信度",
    budgetFactor: "预算匹配",
    completenessFactor: "信息完整度",
    activityFactor: "设施类别",
    weatherFactor: "雨天适配推断",
    modelParser: "OpenAI Responses / Structured Outputs",
    ruleParser: "确定性规则解析",
    formatter: "证据校验格式化"
  }
} satisfies Record<UiLanguage, Record<string, string>>;
